import { decryptDocument, encryptDocument } from "../lib/crypto";
import { isValidRequestOrigin, requireAdminToken } from "../lib/auth";

export async function handleAdminResourceOps(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
  const auth=await requireAdminToken(request,env);if(auth)return auth;if(!["GET","HEAD"].includes(request.method)&&request.headers.has("Cookie")&&!isValidRequestOrigin(request))return json({error:"invalid_origin"},403);
  const url=new URL(request.url);const parts=url.pathname.split("/").filter(Boolean);const projectId=parts[2];const area=parts[3];const detail=parts[4];
  if(!projectId)return json({error:"project_required"},400);
  if(area==="pin")return pin(request,env,projectId,ctx);
  if(area==="tags")return tags(request,env,projectId,ctx);
  if(area==="documents"&&detail)return documents(request,env,projectId,detail,ctx);
  if(area==="backup")return backup(request,env,projectId,ctx);
  if(area==="deployments")return deployments(request,env,projectId,ctx);
  if(area==="benchmarks")return projectBenchmarks(request,env,projectId);
  return json({error:"not_found"},404);
}

async function pin(request:Request,env:Env,projectId:string,ctx:ExecutionContext){if(request.method==="DELETE"){await env.MGMT_DB.prepare(`DELETE FROM project_pins WHERE project_id=?1`).bind(projectId).run();ctx.waitUntil(audit(env,"project.unpinned",{projectId}));return json({ok:true});}if(request.method!=="PUT")return json({error:"method_not_allowed"},405);const body=await bodyJson(request);const rank=Math.max(1,Math.min(9999,Number(body.rank??100)));const now=new Date().toISOString();await env.MGMT_DB.prepare(`INSERT INTO project_pins(project_id,rank,pinned_at) VALUES(?1,?2,?3) ON CONFLICT(project_id) DO UPDATE SET rank=excluded.rank,pinned_at=excluded.pinned_at`).bind(projectId,rank,now).run();ctx.waitUntil(audit(env,"project.pinned",{projectId,rank}));return json({ok:true,rank,pinnedAt:now});}
async function tags(request:Request,env:Env,projectId:string,ctx:ExecutionContext){if(request.method==="GET"){const rows=await env.MGMT_DB.prepare(`SELECT t.id,t.name,t.color FROM tags t JOIN project_tags pt ON pt.tag_id=t.id WHERE pt.project_id=?1 ORDER BY t.name`).bind(projectId).all();return json({data:rows.results??[]});}if(request.method!=="PUT")return json({error:"method_not_allowed"},405);const body=await bodyJson(request);const values=Array.isArray(body.tags)?[...new Set(body.tags.map((value)=>String(value).trim().toLowerCase()).filter(Boolean))].slice(0,30):[];const now=new Date().toISOString();await env.MGMT_DB.prepare(`DELETE FROM project_tags WHERE project_id=?1`).bind(projectId).run();for(const name of values){const id=slug(name);await env.MGMT_DB.prepare(`INSERT INTO tags(id,name,created_at) VALUES(?1,?2,?3) ON CONFLICT(name) DO NOTHING`).bind(id,name,now).run();await env.MGMT_DB.prepare(`INSERT OR IGNORE INTO project_tags(project_id,tag_id,created_at) SELECT ?1,id,?2 FROM tags WHERE name=?3`).bind(projectId,now,name).run();}ctx.waitUntil(audit(env,"project.tags_updated",{projectId,count:values.length}));return json({ok:true,tags:values});}
async function documents(request:Request,env:Env,projectId:string,type:string,ctx:ExecutionContext){if(!["content_md","codebase_map"].includes(type))return json({error:"invalid_document_type"},400);if(!env.CONTENT_ENCRYPTION_KEY)return json({error:"content_encryption_not_configured"},503);const version=env.CONTENT_KEY_VERSION??"v1";if(request.method==="GET"){const row=await env.MGMT_DB.prepare(`SELECT ciphertext,nonce,key_version,content_hash,updated_at FROM project_documents WHERE project_id=?1 AND document_type=?2`).bind(projectId,type).first<{ciphertext:string;nonce:string;key_version:string;content_hash:string;updated_at:string}>();if(!row)return json({error:"not_found"},404);try{const content=await decryptDocument(row.ciphertext,row.nonce,env.CONTENT_ENCRYPTION_KEY,projectId,type,row.key_version);return json({data:{type,content,contentHash:row.content_hash,updatedAt:row.updated_at}});}catch{return json({error:"decryption_failed"},500);}}if(request.method!=="PUT")return json({error:"method_not_allowed"},405);const body=await bodyJson(request);const content=String(body.content??"");if(content.length>1_000_000)return json({error:"document_too_large"},413);const encrypted=await encryptDocument(content,env.CONTENT_ENCRYPTION_KEY,projectId,type,version);const now=new Date().toISOString();const id=crypto.randomUUID();await env.MGMT_DB.prepare(`INSERT INTO project_documents(id,project_id,document_type,ciphertext,nonce,key_version,content_hash,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?8) ON CONFLICT(project_id,document_type) DO UPDATE SET ciphertext=excluded.ciphertext,nonce=excluded.nonce,key_version=excluded.key_version,content_hash=excluded.content_hash,updated_at=excluded.updated_at`).bind(id,projectId,type,encrypted.ciphertext,encrypted.nonce,version,encrypted.contentHash,now).run();ctx.waitUntil(audit(env,"project.document_saved",{projectId,type,contentHash:encrypted.contentHash}));return json({ok:true,contentHash:encrypted.contentHash,updatedAt:now});}
async function backup(request:Request,env:Env,projectId:string,ctx:ExecutionContext){if(request.method==="GET"){const rows=await env.MGMT_DB.prepare(`SELECT * FROM backup_repositories WHERE project_id=?1 ORDER BY updated_at DESC`).bind(projectId).all();return json({data:rows.results??[]});}if(request.method!=="PUT")return json({error:"method_not_allowed"},405);const body=await bodyJson(request);const repositoryUrl=String(body.repositoryUrl??"");try{new URL(repositoryUrl);}catch{return json({error:"invalid_repository_url"},400);}const now=new Date().toISOString();const id=String(body.id??crypto.randomUUID());await env.MGMT_DB.prepare(`INSERT INTO backup_repositories(id,project_id,provider,repository_url,branch,status,created_at,updated_at) VALUES(?1,?2,'github',?3,?4,'unknown',?5,?5) ON CONFLICT(id) DO UPDATE SET repository_url=excluded.repository_url,branch=excluded.branch,updated_at=excluded.updated_at`).bind(id,projectId,repositoryUrl,String(body.branch??"main"),now).run();ctx.waitUntil(audit(env,"project.backup_updated",{projectId,id}));return json({ok:true,id});}
async function deployments(request:Request,env:Env,projectId:string,ctx:ExecutionContext){if(request.method==="GET"){const rows=await env.MGMT_DB.prepare(`SELECT d.*,s.name server_name,s.provider,s.ip_address,s.architecture,s.cpu,s.memory_mb,s.disk_gb,s.operating_system,s.due_at,s.public_url server_url,s.status server_status FROM deployments d JOIN servers s ON s.id=d.server_id WHERE d.project_id=?1 ORDER BY d.updated_at DESC`).bind(projectId).all();return json({data:rows.results??[]});}if(request.method!=="POST")return json({error:"method_not_allowed"},405);const body=await bodyJson(request);if(!body.serverId||!body.environment)return json({error:"server_and_environment_required"},400);const now=new Date().toISOString();const id=String(body.id??crypto.randomUUID());await env.MGMT_DB.prepare(`INSERT INTO deployments(id,project_id,server_id,environment,deployed_url,version,status,deployed_at,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?9) ON CONFLICT(id) DO UPDATE SET server_id=excluded.server_id,environment=excluded.environment,deployed_url=excluded.deployed_url,version=excluded.version,status=excluded.status,deployed_at=excluded.deployed_at,updated_at=excluded.updated_at`).bind(id,projectId,String(body.serverId),String(body.environment),body.deployedUrl??null,body.version??null,String(body.status??"unknown"),body.deployedAt??now,now).run();ctx.waitUntil(audit(env,"project.deployment_updated",{projectId,id}));return json({ok:true,id});}
async function projectBenchmarks(request:Request,env:Env,projectId:string){if(request.method!=="GET")return json({error:"method_not_allowed"},405);const rows=await env.MGMT_DB.prepare(`SELECT * FROM benchmark_candidates WHERE project_id=?1 ORDER BY created_at DESC`).bind(projectId).all();return json({data:rows.results??[]});}
async function bodyJson(request:Request):Promise<Record<string,any>>{try{return await request.json() as Record<string,any>;}catch{return{};}}function slug(value:string){return value.normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-|-$/g,"").slice(0,80)||crypto.randomUUID();}function json(body:unknown,status=200){return Response.json(body,{status,headers:{"Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8"}});}function audit(env:Env,eventType:string,payload:unknown){return env.MGMT_DB.prepare(`INSERT INTO audit_events(event_type,payload,created_at) VALUES(?1,?2,?3)`).bind(eventType,JSON.stringify(payload),new Date().toISOString()).run();}
