import inventory from "../generated/local-projects.json";
import { isValidRequestOrigin, requireAdminToken } from "../lib/auth";

export async function handleAdminProjects(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
  const auth = await requireAdminToken(request, env); if (auth) return auth;
  if (!["GET","HEAD"].includes(request.method) && request.headers.has("Cookie") && !isValidRequestOrigin(request)) return Response.json({ error: "invalid_origin" }, { status: 403 });
  const url = new URL(request.url); const parts = url.pathname.split("/").filter(Boolean); const id = parts[2];
  if (url.pathname === "/admin/projects/import-local" && request.method === "POST") return importLocal(env, ctx);
  if (!id && request.method === "GET") return list(env, url);
  if (id && request.method === "PATCH") return update(request, env, id, ctx);
  if (id && request.method === "DELETE") return remove(env, id, ctx);
  return Response.json({ error: "method_not_allowed" }, { status: 405 });
}

async function list(env: Env, url: URL): Promise<Response> {
  const page=Math.max(Number(url.searchParams.get("page")||1),1),perPage=Math.min(Math.max(Number(url.searchParams.get("per_page")||50),1),100),q=url.searchParams.get("q")?.trim()??"",types=cleanValues(url.searchParams.getAll("type")),platforms=cleanValues(url.searchParams.getAll("platform")),statuses=cleanValues(url.searchParams.getAll("status")),tags=cleanValues(url.searchParams.getAll("tag")),pinned=url.searchParams.get("pinned")??"",deployed=url.searchParams.get("deployed")??"",backup=url.searchParams.get("backup")??"",missing=url.searchParams.get("missing_description")??"",sort=url.searchParams.get("sort")??"priority";
  const where:string[]=[];const values:unknown[]=[];const bind=(value:unknown)=>{values.push(value);return`?${values.length}`;};
  if(q){const pattern=`%${q}%`,a=bind(pattern),b=bind(pattern),c=bind(pattern);where.push(`(p.name LIKE ${a} OR p.description LIKE ${b} OR p.source_ref LIKE ${c})`);}
  if(platforms.length)where.push(`p.platform IN (${platforms.map(value=>bind(value)).join(",")})`);
  if(statuses.length)where.push(`p.status IN (${statuses.map(value=>bind(value)).join(",")})`);
  if(types.length)where.push(`(${types.map(value=>`p.resource_types LIKE ${bind(`%"${value}"%`)}`).join(" OR ")})`);
  if(tags.length)where.push(`EXISTS(SELECT 1 FROM project_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.project_id=p.id AND t.name IN (${tags.map(value=>bind(value)).join(",")}))`);
  if(pinned==="true")where.push(`EXISTS(SELECT 1 FROM project_pins pin WHERE pin.project_id=p.id)`);if(deployed==="true")where.push(`EXISTS(SELECT 1 FROM deployments d WHERE d.project_id=p.id)`);if(deployed==="false")where.push(`NOT EXISTS(SELECT 1 FROM deployments d WHERE d.project_id=p.id)`);if(backup)where.push(`${backup==="configured"?"":"NOT "}EXISTS(SELECT 1 FROM backup_repositories b WHERE b.project_id=p.id)`);if(missing==="true")where.push(`(p.description IS NULL OR TRIM(p.description)='')`);const clause=where.length?`WHERE ${where.join(" AND ")}`:"";
  const order:Record<string,string>={priority:"CASE WHEN last_deployment_at IS NULL THEN 1 ELSE 0 END,last_deployment_at DESC,CASE WHEN last_backup_at IS NULL THEN 1 ELSE 0 END,last_backup_at DESC,CASE WHEN pin_rank IS NULL THEN 1 ELSE 0 END,pin_rank,COALESCE(p.source_updated_at,p.updated_at) DESC",deployment_desc:"CASE WHEN last_deployment_at IS NULL THEN 1 ELSE 0 END,last_deployment_at DESC",backup_desc:"CASE WHEN last_backup_at IS NULL THEN 1 ELSE 0 END,last_backup_at DESC",updated_desc:"COALESCE(p.source_updated_at,p.updated_at) DESC",name:"p.name",pin:"CASE WHEN pin_rank IS NULL THEN 1 ELSE 0 END,pin_rank",scan_desc:"p.last_scanned_at DESC"};const orderBy=order[sort]??order.priority;
  const totalRow=await env.MGMT_DB.prepare(`SELECT COUNT(*) AS total FROM catalog_projects p ${clause}`).bind(...values).first<{total:number}>(); const offset=(page-1)*perPage;
  const rows=await env.MGMT_DB.prepare(`SELECT p.*,(SELECT GROUP_CONCAT(t.name) FROM project_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.project_id=p.id) tag_names,(SELECT rank FROM project_pins WHERE project_id=p.id) pin_rank,(SELECT COUNT(*) FROM deployments WHERE project_id=p.id) deployment_count,(SELECT MAX(COALESCE(deployed_at,updated_at,created_at)) FROM deployments WHERE project_id=p.id) last_deployment_at,(SELECT status FROM backup_repositories WHERE project_id=p.id ORDER BY updated_at DESC LIMIT 1) backup_status,(SELECT MAX(COALESCE(last_backup_at,last_verified_at,updated_at,created_at)) FROM backup_repositories WHERE project_id=p.id AND provider='github') last_backup_at FROM catalog_projects p ${clause} ORDER BY ${orderBy} LIMIT ?${values.length+1} OFFSET ?${values.length+2}`).bind(...values,perPage,offset).all<Record<string,unknown>>();
  const baseRows=rows.results??[],ids=baseRows.map(value=>String(value.id)),deploymentsByProject=new Map<string,Record<string,unknown>[]>(),snapshotsByProject=new Map<string,Record<string,unknown>>();
  if(ids.length){const placeholders=ids.map((_,index)=>`?${index+1}`).join(",");const [deploymentRows,snapshotRows]=await Promise.all([env.MGMT_DB.prepare(`SELECT d.id,d.project_id,d.environment,d.deployed_url,d.version,d.status,d.deployed_at,d.health_status,d.last_checked_at,d.last_latency_ms,d.last_error,s.id server_id,s.name server_name,s.provider server_provider,s.health_status server_health_status,s.cloud_status server_cloud_status,s.last_checked_at server_last_checked_at FROM deployments d JOIN servers s ON s.id=d.server_id WHERE d.project_id IN (${placeholders}) ORDER BY COALESCE(d.deployed_at,d.updated_at) DESC`).bind(...ids).all<Record<string,unknown>>(),env.MGMT_DB.prepare(`SELECT * FROM repository_snapshots WHERE project_id IN (${placeholders}) ORDER BY updated_at DESC`).bind(...ids).all<Record<string,unknown>>()]);for(const deployment of deploymentRows.results??[]){const key=String(deployment.project_id),group=deploymentsByProject.get(key)??[];group.push(deployment);deploymentsByProject.set(key,group);}for(const snapshot of snapshotRows.results??[]){const key=String(snapshot.project_id);if(!snapshotsByProject.has(key))snapshotsByProject.set(key,snapshot);}}
  const [stats,pinnedCount,missingCount]=await Promise.all([env.MGMT_DB.prepare(`SELECT platform,status,COUNT(*) AS count FROM catalog_projects GROUP BY platform,status`).all<{platform:string;status:string;count:number}>(),env.MGMT_DB.prepare(`SELECT COUNT(*) count FROM project_pins`).first<{count:number}>(),env.MGMT_DB.prepare(`SELECT COUNT(*) count FROM catalog_projects WHERE description IS NULL OR TRIM(description)=''`).first<{count:number}>()]);
  const localRoot=env.LOCAL_SCAN_ROOT??(env.ENVIRONMENT==="development"?"/Users/af/cpro01":undefined);
  return Response.json({ data:baseRows.map(value=>row(value,localRoot,deploymentsByProject.get(String(value.id))??[],snapshotsByProject.get(String(value.id)))),meta:{page,perPage,total:totalRow?.total??0,pages:Math.ceil((totalRow?.total??0)/perPage),localScanCount:inventory.count,localScanAt:inventory.generatedAt,pinnedCount:Number(pinnedCount?.count??0),missingCount:Number(missingCount?.count??0),stats:stats.results??[]} });
}

async function importLocal(env: Env, ctx: ExecutionContext): Promise<Response> {
  const now=new Date().toISOString(); let imported=0;
  for(let index=0;index<inventory.resources.length;index+=50){const chunk=inventory.resources.slice(index,index+50);const statements=chunk.map((item)=>env.MGMT_DB.prepare(`INSERT INTO catalog_projects (id,name,description,resource_types,platform,source_kind,source_ref,repository_url,languages,frameworks,status,visibility,discovered_at,updated_at,metadata,source_updated_at,last_scanned_at,update_provenance) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=COALESCE(catalog_projects.description,excluded.description),resource_types=excluded.resource_types,platform=excluded.platform,source_kind=excluded.source_kind,source_ref=excluded.source_ref,repository_url=COALESCE(excluded.repository_url,catalog_projects.repository_url),languages=excluded.languages,frameworks=excluded.frameworks,updated_at=excluded.updated_at,metadata=excluded.metadata,source_updated_at=excluded.source_updated_at,last_scanned_at=excluded.last_scanned_at,update_provenance=excluded.update_provenance`).bind(item.id,item.name,item.description,JSON.stringify(item.resourceTypes),item.platform,item.sourceKind,item.sourceRef,item.repositoryUrl,JSON.stringify(item.languages),JSON.stringify(item.frameworks),item.status,item.visibility,item.discoveredAt,now,JSON.stringify(item.metadata),item.sourceUpdatedAt,item.lastScannedAt,JSON.stringify({source:"local_scan",scannedAt:item.lastScannedAt})));await env.MGMT_DB.batch(statements);imported+=chunk.length;}
  ctx.waitUntil(audit(env,"catalog.local_import",{imported,scanAt:inventory.generatedAt}));
  return Response.json({ok:true,imported,scanAt:inventory.generatedAt});
}

async function update(request:Request,env:Env,id:string,ctx:ExecutionContext){let input:Record<string,unknown>;try{input=await request.json();}catch{return Response.json({error:"invalid_json"},{status:400});}const allowed=["name","description","status","visibility","homepage","repository_url"];const sets=[];const values:unknown[]=[];for(const key of allowed)if(Object.hasOwn(input,key)){sets.push(`${key} = ?${values.length+1}`);values.push(input[key]);}if(!sets.length)return Response.json({error:"no_supported_fields"},{status:400});sets.push(`updated_at = ?${values.length+1}`);values.push(new Date().toISOString(),id);const result=await env.MGMT_DB.prepare(`UPDATE catalog_projects SET ${sets.join(", ")} WHERE id = ?${values.length}`).bind(...values).run();if(!result.meta?.changes)return Response.json({error:"not_found"},{status:404});ctx.waitUntil(audit(env,"catalog.project_updated",{id,fields:Object.keys(input)}));return Response.json({ok:true,id});}
async function remove(env:Env,id:string,ctx:ExecutionContext){const result=await env.MGMT_DB.prepare(`DELETE FROM catalog_projects WHERE id = ?1`).bind(id).run();if(!result.meta?.changes)return Response.json({error:"not_found"},{status:404});ctx.waitUntil(audit(env,"catalog.project_deleted",{id}));return Response.json({ok:true,id});}
function row(value:Record<string,unknown>,root:string|undefined,deployments:Record<string,unknown>[],snapshot?:Record<string,unknown>){const sourceRef=String(value.source_ref??"");const repositoryUrl=String(snapshot?.repository_url??value.repository_url??"")||null;return{id:value.id,name:value.name,description:value.description,resourceTypes:parse(value.resource_types),platform:value.platform,sourceKind:value.source_kind,sourceRef,localPath:root?`${root.replace(/\/$/,"")}/${sourceRef.replace(/^\.\/?/,"")}`:sourceRef,homepage:value.homepage,repositoryUrl,languages:parse(value.languages),frameworks:parse(value.frameworks),status:value.status,visibility:value.visibility,discoveredAt:value.discovered_at,updatedAt:value.updated_at,sourceUpdatedAt:value.source_updated_at,lastScannedAt:value.last_scanned_at,metadata:object(value.metadata),tags:value.tag_names?String(value.tag_names).split(","):[],pinRank:value.pin_rank,deploymentCount:Number(value.deployment_count??0),lastDeploymentAt:value.last_deployment_at,backupStatus:value.backup_status,lastBackupAt:value.last_backup_at,repository:snapshot?{url:repositoryUrl,owner:snapshot.github_owner,repo:snapshot.github_repo,headSha:snapshot.head_sha,branch:snapshot.branch,pushedAt:snapshot.pushed_at,ahead:snapshot.ahead,behind:snapshot.behind,dirty:Boolean(snapshot.dirty),lastScannedAt:snapshot.last_scanned_at,metadata:object(snapshot.github_metadata)}:repositoryUrl?{url:repositoryUrl}:null,deployments:deployments.map(deployment=>({id:deployment.id,environment:deployment.environment,url:deployment.deployed_url,version:deployment.version,status:deployment.status,deployedAt:deployment.deployed_at,healthStatus:deployment.health_status,lastCheckedAt:deployment.last_checked_at,latencyMs:deployment.last_latency_ms,lastError:deployment.last_error,server:{id:deployment.server_id,name:deployment.server_name,provider:deployment.server_provider,healthStatus:deployment.server_health_status,cloudStatus:deployment.server_cloud_status,lastCheckedAt:deployment.server_last_checked_at}}))};}
function cleanValues(values:string[]){return[...new Set(values.map(value=>value.trim().toLowerCase()).filter(Boolean))].slice(0,20);}
function parse(value:unknown){try{const result=JSON.parse(String(value));return Array.isArray(result)?result:[];}catch{return[];}}function object(value:unknown){try{return JSON.parse(String(value));}catch{return{};}}
function audit(env:Env,eventType:string,payload:unknown){return env.MGMT_DB.prepare(`INSERT INTO audit_events (event_type,payload,created_at) VALUES (?1,?2,?3)`).bind(eventType,JSON.stringify(payload),new Date().toISOString()).run();}
