import { isValidRequestOrigin, requireAdminToken } from "../lib/auth";

export async function handleAdminAssets(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
  const auth=await requireAdminToken(request,env);if(auth)return auth;
  if(!["GET","HEAD"].includes(request.method)&&request.headers.has("Cookie")&&!isValidRequestOrigin(request))return json({error:"invalid_origin"},403);
  const url=new URL(request.url),parts=url.pathname.split("/").filter(Boolean),action=parts[2],id=parts[3];
  if(action==="summary"&&request.method==="GET")return summary(env);
  if(action==="import"&&request.method==="POST")return importAssets(request,env,ctx);
  if(id&&request.method==="GET")return detail(env,id);
  if(!action&&request.method==="GET")return list(env,url);
  return json({error:"method_not_allowed"},405);
}

async function list(env:Env,url:URL){
  const page=Math.max(1,Number(url.searchParams.get("page")||1)),perPage=Math.min(100,Math.max(1,Number(url.searchParams.get("per_page")||50))),filters:{column:string,value:string}[]=[];
  for(const [param,column] of [["provider","provider"],["account","account_id"],["kind","kind"],["status","status"],["region","region"],["server","server_id"]] as const){const value=url.searchParams.get(param)?.trim();if(value)filters.push({column,value});}
  const values:unknown[]=[],where:string[]=[];
  if(url.searchParams.get("scope")==="cloud")where.push("provider IN ('tencent','cloudflare','godaddy','ens','solana')");
  for(const filter of filters){values.push(filter.value);where.push(`${filter.column}=?${values.length}`);}
  const probe=url.searchParams.get("probe")?.trim();
  if(probe==="pending")where.push("kind IN ('dns_record','pages_project') AND status IN ('enable','active','available') AND (kind='pages_project' OR json_extract(metadata,'$.type') IN ('A','CNAME')) AND json_extract(metadata,'$.probe.status') IS NULL");
  else if(probe){values.push(probe);where.push(`json_extract(metadata,'$.probe.status')=?${values.length}`);}
  const q=url.searchParams.get("q")?.trim();
  if(q){values.push(`%${q}%`);where.push(`(name LIKE ?${values.length} OR external_id LIKE ?${values.length} OR url LIKE ?${values.length})`);}
  const linked=url.searchParams.get("linked");
  if(linked==="true")where.push("(project_id IS NOT NULL OR EXISTS(SELECT 1 FROM resource_links l WHERE l.source_asset_id=discovered_assets.id AND l.status='confirmed'))");
  if(linked==="false")where.push("project_id IS NULL AND NOT EXISTS(SELECT 1 FROM resource_links l WHERE l.source_asset_id=discovered_assets.id AND l.status='confirmed')");
  const expiry=`COALESCE(json_extract(metadata,'$.expiresAt'),json_extract(metadata,'$.expiredAt'),json_extract(metadata,'$.deadline'),json_extract(metadata,'$.dueAt'))`;
  const expiringParam=url.searchParams.get("expiring_days"),expiringDays=expiringParam===null?NaN:Number(expiringParam);
  if(Number.isFinite(expiringDays)&&expiringDays>=0&&expiringDays<=7300)where.push(`${expiry} IS NOT NULL AND datetime(${expiry}) BETWEEN datetime('now','-1 day') AND datetime('now','+${Math.floor(expiringDays)} days')`);
  const clause=where.length?`WHERE ${where.join(" AND ")}`:"",total=await env.MGMT_DB.prepare(`SELECT COUNT(*) count FROM discovered_assets ${clause}`).bind(...values).first<{count:number}>(),offset=(page-1)*perPage;
  const order=url.searchParams.get("sort")==="expires"?`CASE WHEN ${expiry} IS NULL THEN 1 ELSE 0 END, datetime(${expiry}) ASC, name`:`CASE WHEN stale_after IS NOT NULL AND stale_after<CURRENT_TIMESTAMP THEN 1 ELSE 0 END,status,name`;
  const rows=await env.MGMT_DB.prepare(`SELECT * FROM discovered_assets ${clause} ORDER BY ${order} LIMIT ?${values.length+1} OFFSET ?${values.length+2}`).bind(...values,perPage,offset).all<Record<string,unknown>>();
  return json({data:(rows.results??[]).map(asset),meta:{page,perPage,total:Number(total?.count??0),pages:Math.ceil(Number(total?.count??0)/perPage)}});
}

async function summary(env:Env){
  const expiry=`COALESCE(json_extract(metadata,'$.expiresAt'),json_extract(metadata,'$.expiredAt'),json_extract(metadata,'$.deadline'),json_extract(metadata,'$.dueAt'))`;
  const [groups,runs,links,expiring]=await Promise.all([env.MGMT_DB.prepare(`SELECT provider,kind,status,COUNT(*) count FROM discovered_assets WHERE status!='stale' GROUP BY provider,kind,status ORDER BY provider,kind,status`).all(),env.MGMT_DB.prepare(`SELECT * FROM asset_discovery_runs r WHERE started_at=(SELECT MAX(started_at) FROM asset_discovery_runs WHERE provider=r.provider AND account_id=r.account_id) ORDER BY provider,account_id`).all(),env.MGMT_DB.prepare(`SELECT status,COUNT(*) count FROM resource_links GROUP BY status`).all(),env.MGMT_DB.prepare(`SELECT id,provider,account_id,kind,name,status,url,metadata,last_verified_at FROM discovered_assets WHERE status!='stale' AND ${expiry} IS NOT NULL AND datetime(${expiry})>=datetime('now','-1 day') ORDER BY datetime(${expiry}) ASC LIMIT 20`).all<Record<string,unknown>>()]);
  return json({data:{groups:groups.results??[],latestRuns:runs.results??[],links:links.results??[],expiring:(expiring.results??[]).map(asset)}});
}

async function detail(env:Env,id:string){const row=await env.MGMT_DB.prepare(`SELECT * FROM discovered_assets WHERE id=?1`).bind(id).first<Record<string,unknown>>();if(!row)return json({error:"not_found"},404);const links=await env.MGMT_DB.prepare(`SELECT l.*,p.name project_name,t.name target_name FROM resource_links l LEFT JOIN catalog_projects p ON p.id=l.project_id LEFT JOIN discovered_assets t ON t.id=l.target_asset_id WHERE l.source_asset_id=?1 OR l.target_asset_id=?1 ORDER BY l.confidence DESC`).bind(id).all();return json({data:{...asset(row),links:links.results??[]}});}

async function importAssets(request:Request,env:Env,ctx:ExecutionContext){const body=await request.json().catch(()=>null) as any;if(!body||!Array.isArray(body.assets)||!body.provider)return json({error:"invalid_asset_batch"},400);const now=new Date().toISOString(),seenAt=typeof body.scanAt==="string"?body.scanAt:now,seen=new Set<string>();for(let i=0;i<body.assets.length;i+=50){const chunk=body.assets.slice(i,i+50),statements=chunk.map((input:any)=>{const provider=String(input.provider||body.provider),account=String(input.accountId||body.accountId||"default"),kind=String(input.kind||"unknown"),externalId=String(input.externalId||input.name||crypto.randomUUID()),id=String(input.id||stableId(provider,account,kind,externalId));seen.add(id);return env.MGMT_DB.prepare(`INSERT INTO discovered_assets(id,provider,account_id,kind,external_id,parent_external_id,name,status,region,url,server_id,project_id,metadata,first_seen_at,last_seen_at,last_verified_at,stale_after,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?14,?14,?15,?14,?16) ON CONFLICT(provider,account_id,kind,external_id) DO UPDATE SET parent_external_id=excluded.parent_external_id,name=excluded.name,status=excluded.status,region=excluded.region,url=excluded.url,server_id=COALESCE(excluded.server_id,discovered_assets.server_id),project_id=COALESCE(excluded.project_id,discovered_assets.project_id),metadata=excluded.metadata,last_seen_at=excluded.last_seen_at,last_verified_at=excluded.last_verified_at,stale_after=excluded.stale_after,updated_at=excluded.updated_at`).bind(id,provider,account,kind,externalId,input.parentExternalId??null,String(input.name||externalId),String(input.status||"unknown"),input.region??null,input.url??null,input.serverId??null,input.projectId??null,JSON.stringify(input.metadata??{}),seenAt,input.staleAfter??new Date(Date.parse(seenAt)+Number(body.staleAfterMs||86_400_000)).toISOString(),now);});await env.MGMT_DB.batch(statements);}
  if(String(body.provider)==="tencent")for(const input of body.assets.filter((asset:any)=>["cvm","lighthouse"].includes(String(asset.kind)))){const publicIp=Array.isArray(input.metadata?.publicIps)?input.metadata.publicIps[0]:null;if(!publicIp)continue;await env.MGMT_DB.prepare(`UPDATE servers SET provider_resource_id=?1,cloud_status=?2,cloud_checked_at=?3,cpu=COALESCE(?4,cpu),memory_mb=COALESCE(?5,memory_mb),disk_gb=COALESCE(?6,disk_gb),due_at=COALESCE(?7,due_at),updated_at=?3 WHERE provider LIKE 'tencent%' AND ip_address=?8`).bind(String(input.externalId),String(input.status||"unknown"),seenAt,input.metadata?.cpu!=null?`${input.metadata.cpu} vCPU`:null,input.metadata?.memoryMb??null,input.metadata?.diskGb??null,input.metadata?.expiredAt??null,String(publicIp)).run();}
  if(body.complete===true){
    if(String(body.provider)==="docker"&&body.assets.some((asset:any)=>asset.serverId)){
      const serverId=String(body.assets.find((asset:any)=>asset.serverId)?.serverId);
      await env.MGMT_DB.prepare(`UPDATE discovered_assets SET status='stale',updated_at=?1 WHERE provider='docker' AND server_id=?2 AND last_seen_at<?3`).bind(now,serverId,seenAt).run();
    }else await env.MGMT_DB.prepare(`UPDATE discovered_assets SET status='stale',updated_at=?1 WHERE provider=?2 AND account_id=?3 AND last_seen_at<?4`).bind(now,String(body.provider),String(body.accountId||"default"),seenAt).run();
    if(["cloudflare","godaddy"].includes(String(body.provider)))await env.MGMT_DB.prepare(`UPDATE discovered_assets SET status='stale',updated_at=?1 WHERE provider=?2 AND kind='credential_status' AND account_id!=?3`).bind(now,String(body.provider),String(body.accountId||"default")).run();
  }
  if(Array.isArray(body.links))for(const link of body.links){const id=stableId("link",String(link.sourceAssetId),String(link.targetAssetId||link.projectId||""),String(link.relationship));await env.MGMT_DB.prepare(`INSERT INTO resource_links(id,source_asset_id,target_asset_id,project_id,relationship,confidence,status,evidence,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?9) ON CONFLICT(source_asset_id,target_asset_id,project_id,relationship) DO UPDATE SET confidence=excluded.confidence,status=excluded.status,evidence=excluded.evidence,updated_at=excluded.updated_at`).bind(id,link.sourceAssetId,link.targetAssetId??null,link.projectId??null,String(link.relationship),Number(link.confidence??1),String(link.status??"confirmed"),JSON.stringify(link.evidence??[]),now).run();}
  if(body.complete===true&&body.run){const runId=String(body.run.id||stableId("run",String(body.provider),String(body.accountId||"default"),String(body.run.startedAt||now))),providerErrors=Array.isArray(body.run.errors)?body.run.errors:[],status=providerErrors.length?"partial":"complete";await env.MGMT_DB.prepare(`INSERT INTO asset_discovery_runs(id,provider,account_id,mode,status,discovered_count,changed_count,stale_count,duration_ms,error_code,error_message,started_at,completed_at,created_at) VALUES(?1,?2,?3,?4,?5,?6,?6,0,?7,?8,?9,?10,?11,?10) ON CONFLICT(id) DO UPDATE SET status=excluded.status,discovered_count=excluded.discovered_count,changed_count=excluded.changed_count,duration_ms=excluded.duration_ms,error_code=excluded.error_code,error_message=excluded.error_message,completed_at=excluded.completed_at`).bind(runId,String(body.provider),String(body.accountId||"default"),String(body.run.mode||"incremental"),status,Number(body.run.discoveredCount||body.assets.length),Number(body.run.durationMs||0),providerErrors[0]?.code??null,providerErrors.map((value:any)=>value.message).join("; ").slice(0,1000)||null,String(body.run.startedAt||now),now).run();}
  if(body.complete===true&&body.run){const provider=String(body.provider),providerErrors=Array.isArray(body.run.errors)?body.run.errors:[],firstError=providerErrors[0],credentialStatus=firstError?.code==="not_configured"?"unconfigured":firstError?.scope==="authentication"?"error":"configured";ctx.waitUntil(env.MGMT_DB.prepare(`UPDATE source_connectors SET credential_status=?1,last_success_at=CASE WHEN ?2='configured' THEN ?3 ELSE last_success_at END,next_due_at=datetime('now','+' || interval_seconds || ' seconds'),last_error_code=?4,last_error_message=?5,updated_at=?3 WHERE provider=?6`).bind(credentialStatus,credentialStatus,now,firstError?.code??null,firstError?.message??null,provider).run());}
  ctx.waitUntil(env.MGMT_DB.prepare(`INSERT INTO audit_events(event_type,payload,created_at) VALUES('assets.imported',?1,?2)`).bind(JSON.stringify({provider:body.provider,accountId:body.accountId||"default",count:body.assets.length}),now).run());return json({ok:true,imported:body.assets.length,seen:[...seen].length});
}

function asset(value:Record<string,unknown>){return{...value,metadata:parseObject(value.metadata),isStale:Boolean(value.stale_after&&String(value.stale_after)<new Date().toISOString())};}function parseObject(value:unknown){try{return JSON.parse(String(value));}catch{return{};}}function stableId(...parts:string[]){let hash=2166136261;for(const char of parts.join("\0")){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return`asset-${(hash>>>0).toString(16).padStart(8,"0")}`;}function json(body:unknown,status=200){return Response.json(body,{status,headers:{"Cache-Control":"no-store"}});}
